name: Build Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install cross-compilation toolchains
        run: |
          sudo apt update
          sudo apt install -y --force-yes gcc g++
          sudo apt install -y --force-yes gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
          sudo apt install -y --force-yes gcc-riscv64-linux-gnu g++-riscv64-linux-gnu libc6-dev-riscv64-cross
          sudo apt install -y --force-yes mingw-w64 lib32z1

      - name: Download Android NDK
        run: |
          mkdir -p $HOME/android-ndk
          cd $HOME/android-ndk
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip -O android-ndk.zip
          echo "769ee342ea75f80619d985c2da990c48b3d8eaf45f48783a2d48870d04b46108  android-ndk.zip" | sha256sum --check
          unzip android-ndk.zip
          echo "NDK_HOME=$HOME/android-ndk/android-ndk-r25c" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build box2d
        run: ./gradlew build_linux build_android build_windows

      - name: Initialize jnigen
        run: ./gradlew jnigen

      - name: Build natives
        run: ./gradlew jnigenBuildAllLinux jnigenBuildAllWindows jnigenBuildAndroid_x86_64 jnigenBuildAndroid_arm64-v8a


      - name: Pack artifacts
        run: |
          find .  -name "*.a" -o -name "*.dll" -o -name "*.dylib" -o -name "*.so" | grep "libs" > native-files-list
          zip natives -@ < native-files-list

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: natives.zip
          path: natives.zip

  publish:
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
        contents: read
        packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Download Artifacts from linux
        uses: actions/download-artifact@v4
        with:
          name: natives.zip

      - name: Unzip artifacts
        run: unzip -o natives.zip

      - name: Package All
        run: ./gradlew jnigenPackageAll

      - name: Snapshot build deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'k88936'
        run: |
          ./gradlew build publish -x test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
